using Tyuiu.RadchenkoAV.Sprint3.Task2.V13.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #3 | Выполнил: Радченко А. В. | РППБ-25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #3                                                               *");
Console.WriteLine("* Тема: Оператор цикла do while                                           *");
Console.WriteLine("* Задание #2                                                              *");
Console.WriteLine("* Варинант #13                                                            *");
Console.WriteLine("* Выполнил: Радченко А. В. | РППБ-25-1                                    *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("*Написать программу используя цикл do...while, которая вычисляет сумму*****");
Console.WriteLine("*ряда по формуле, при t=0,7************************************************");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
int startValue = 1;
double value = 0.7;
int stopValue = 10;
Console.WriteLine("Переменная X = " + value);
Console.WriteLine("Старт шага = " + startValue);
Console.WriteLine("Конец шага = " + stopValue);
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("Сумма ряда = " + ds.GetSumSeries(value, startValue, stopValue));
Console.ReadLine();