using Tyuiu.RadchenkoAV.Sprint3.Task6.V24.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #3 | Выполнил: Радченко А. В. | РППБ-25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #3                                                               *");
Console.WriteLine("* Тема: Обработка целочисленной информации                                *");
Console.WriteLine("* Задание #6                                                              *");
Console.WriteLine("* Вариант #24                                                             *");
Console.WriteLine("* Выполнил: Радченко А. В. | РППБ-25-1                                    *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Написать программу, которая ищет среди целых чисел, принадлежащих       *");
Console.WriteLine("* числовому отрезку [17,26] количество всех делителей                     *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
int startValue = 17;
int stopValue = 26;
Console.WriteLine("* Начало отрезка = " + startValue);
Console.WriteLine("* Конец отрезка = " + stopValue);
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
double res = ds.GetSumTheDivisors(startValue, stopValue);
Console.WriteLine("* Количество делителей = " + res);